Ajuste para validación de cobertura

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -69,6 +69,8 @@ jobs:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
+      - name: Install dependencies
+        run: sudo apt-get install -y bc
       - name: Grant execute permission for mvnw
         run: chmod +x ./${{ matrix.service }}/mvnw
       - name: Build, test, and analyze
@@ -84,6 +86,9 @@ jobs:
           -Dsonar.java.source=${{ env.JAVA_VERSION }} \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
           -Dsonar.qualitygate.wait=true
+          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
+          -Dsonar.pullrequest.branch=${{ github.head_ref }} \
+          -Dsonar.pullrequest.base=${{ github.base_ref }}
       - name: Check Quality Gate
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -94,6 +99,33 @@ jobs:
           if [ "$QUALITY_GATE_STATUS" = "ERROR" ]; then
             echo "Quality Gate failed!"
             exit 1
+          fi
+      - name: Check Overall Coverage
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          cd ${{ matrix.service }}
+          
+          echo "Waiting for SonarQube analysis to be fully processed..."
+          sleep 20
+          
+          echo "Checking overall code coverage..."
+          COVERAGE=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/measures/component?component=${{ secrets.SONAR_PROJECT_KEY }}${{ matrix.sonar_project_id }}&metricKeys=coverage" | jq -r '.component.measures[0].value')
+          
+          if [ -z "$COVERAGE" ] || [ "$COVERAGE" == "null" ]; then
+            echo "Error: Could not retrieve coverage data from SonarQube API"
+            exit 1
+          fi
+          
+          echo "Overall coverage: ${COVERAGE}%"
+          
+          COVERAGE_NUM=$(echo $COVERAGE | sed 's/,/./g')
+          
+          if (( $(echo "$COVERAGE_NUM < 80.0" | bc -l) )); then
+            echo "Error: Overall code coverage is ${COVERAGE}%, which is below the required threshold of 80%"
+            exit 1
+          else
+            echo "Success: Overall code coverage is ${COVERAGE}%, which meets or exceeds the required threshold of 80%"
           fi
 
   build-and-push:
